GET http://localhost:8080/ChallengingEveryDaySpring/api/buttons
###

POST http://localhost:8080/ChallengingEveryDaySpring/api/buttons
Content-Type: application/json

{
  "challenge_id": 50,
  "name": "te",
  "num": 50
}

###

PUT http://localhost:8080/ChallengingEveryDaySpring/api/buttons/13
Content-Type: application/json

{
  "challenge_id": 5,
  "name": "t",
  "num": 5
}

###
DELETE http://localhost:8080/ChallengingEveryDaySpring/api/buttons/13