GET http://localhost:8080/ChallengingEveryDaySpring/api/challenges

###

POST http://localhost:8080/ChallengingEveryDaySpring/api/challenges
Content-Type: application/json

{
  "client_id": 1000,
  "name": "Ne",
  "need": 1000,
  "days": 1000,
  "start_date": 1658674000000
}

###

PUT http://localhost:8080/ChallengingEveryDaySpring/api/challenges/5
Content-Type: application/json

{

  "client_id": 1000,
  "name": "Nene",
  "need": 1000,
  "days": 1000,
  "start_date": 1658800000000
}

###
DELETE http://localhost:8080/ChallengingEveryDaySpring/api/challenges/5